server:
  port: 8089

spring:
  application:
    name: notification-service
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
      - configserver:${CONFIG_SERVER_URL}
  data:
    mongodb:
      uri: ${MONGO_URI}
