server:
  port: 8085

spring:
  application:
    name: order-service
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
      - configserver:${CONFIG_SERVER_URL}

feign:
  circuitbreaker:
    enabled: true
