server:
  port: 8092

spring:
  application:
    name: metrics-exporter
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
      - configserver:${CONFIG_SERVER_URL}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL}
