server:
  port: 8086

spring:
  application:
    name: payment-service
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
      - configserver:${CONFIG_SERVER_URL}
