server:
  port: 8086

spring:
  application:
    name: payment-service
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
      - configserver:http://${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8888}
