# ─────────────────────────────────────────────────────────────────
# auth-service specific config — overrides shared application.yml
# ─────────────────────────────────────────────────────────────────

spring:
  data:
    mongodb:
      database: auth_db

jwt:
  secret-key: ${JWT_SECRET_KEY}
  expiry-minutes: ${JWT_EXPIRY_TIME_IN_MINUTE:15}
  refresh-expiry-days: ${JWT_REFRESH_EXPIRY_DAYS:30}

otp:
  expiry-minutes: ${OTP_EXPIRY_MINUTES:5}

password-reset:
  expiry-minutes: ${PASSWORD_RESET_EXPIRY_MINUTES:15}
