# ─────────────────────────────────────────────────────────────────
# user-service specific config — overrides shared application.yml
# ─────────────────────────────────────────────────────────────────

spring:
  data:
    mongodb:
      database: user_db
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
