server:
  port: 8087

spring:
  application:
    name: cart-service
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
      - configserver:http://${CONFIG_SERVER_HOST:localhost}:${CONFIG_SERVER_PORT:8888}

feign:
  circuitbreaker:
    enabled: true
