server:
  port: 8091

spring:
  application:
    name: review-service
  data:
    mongodb:
      uri: ${MONGO_URI}
      database: review_db
  config:
    import:
      - optional:file:.env[.properties]
      - optional:file:../.env[.properties]
      - configserver:${CONFIG_SERVER_URL}

feign:
  circuitbreaker:
    enabled: true
